theme: jekyll-theme-midnight
title: <a href='/'>Blog</a>
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - blog.md
  - achievements.md
  - _posts
