theme: jekyll-theme-midnight
title: <a href='/'><img src='https://github.com/pligonstein/pligonstein.github.io/blob/main/images/af215e5fff666eac8ced013e66f9a6c1.gif' alt='Home' style='height: 40px;'></a>
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - blog.md
  - achievements.md
  - _posts
