theme: jekyll-theme-midnight
title: Blog
description: MEMEMEMEMEME
show_github_link: false
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
