theme: jekyll-theme-midnight
title: "<a href='/'><img src='https://raw.githubusercontent.com/pligonstein/pligonstein.github.io/main/images/af215e5fff666eac8ced013e66f9a6c1.gif' style='height: 24px;'></a>"
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - blog.md
  - achievements.md
  - _posts
