theme: jekyll-theme-midnight
title: "Plig's Blog"
sass:
  style: compressed
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.html
  - blog.md
  - achievements.md
  - _posts
  - assets/css/style.scss
  - _layouts/default.html
  - _layouts/post.html
